### PR TITLE
fix: youtube player not initialized when another player was initizlied in other component/page

### PR DESCRIPTION
**Pull request by flowdeskadmin**

### CODE REVIEW

**Comment by flowdeskadmin** [comment]
@orizens Please update npm as well

**Comment by orizens** [comment]
npm is updated with new ngx-youtube-player versions: 9, 10,11 and 12

**Comment by flowdeskadmin** [comment]
I can see that my changes are not live in master branch

**Comment by orizens** [comment]
Yeah, my bad. Can you update your branch and reopen ?

**Comment by orizens** [comment]
hi @mobilestar1 i released your fix in v 12.0.1

**Comment by flowdeskadmin** [comment]
@orizens thanks

**Pull request merged**
